### ISSUE TITLE
None of these changes have made it into powershell help yet. 

### ISSUE THREAD

**Issue by AbfSailor** [MicrosoftDocs/sccm-docs-powershell-ref#109]
We're taught to rely on Powershell Get-Help. It's been 10 months and these changes still have not been updated in the help files for this module. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83b95889-e52a-5cc6-eebf-630d9abb3522
* Version Independent ID: 73e4b737-e9f9-27ee-6ee5-0ad0ef1afddd
* Content: [Version 1810 release notes - Configuration Manager](https://docs.microsoft.com/en-us/powershell/sccm/1810-release-notes?view=sccm-ps)
* Content Source: [docs-conceptual/1810-release-notes.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/docs-conceptual/1810-release-notes.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @AbfSailor for taking the time to provide feedback on Configuration Manager! I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by AbfSailor** [comment]
Hey @aczechowski 
Thank you for responding so quickly. I'm sorry I should have stated that the Microsoft Docs page is also out of date. Who is responsible for updating Microsoft Docs?

Thank you for the direction to the SCCM product feedback, I'll inform them that the SCCM module help files are out of date. 

Kind Regards,
AbfSailor

**Comment by aczechowski** [comment]
That's me and my team. Unfortunately we have a large backlog of work for the PowerShell & SDK content, but are looking at ways to improve it in the future. The release notes are currently the best record of changes to PowerShell cmdlets.
