### ISSUE TITLE
Deployment Package vs. Software Update Package

### ISSUE THREAD

**Issue by heinejeppesen** [MicrosoftDocs/sccm-docs-powershell-ref#112]
It's not very logically that "Deployment" package means software update packages.
Pretty much everything ConfigMgr does is deployment - not just software updates.

And it's called Software Update Packages in the console.

Same for Operating System Images and System Installer.
They are called Images and Upgrade Packages in the console.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fcba1a4-9a0b-c34c-1c55-4d9c4fe52128
* Version Independent ID: d3a8950d-f0aa-3dfd-8cd9-b656c9617283
* Content: [Publish-CMPrestageContent - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/publish-cmprestagecontent?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/Publish-CMPrestageContent.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Publish-CMPrestageContent.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @heinejeppesen for taking the time to provide feedback on Configuration Manager! I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
