### ISSUE TITLE
Examples starting with C:\> will never work when copy/pasted

### ISSUE THREAD

**Issue by merlinfrombelgium** [MicrosoftDocs/sccm-docs-powershell-ref#116]
I'm noticing a lot of the examples starting with C:\>

Assuming this information will be read and used by peers who are just starting out with PowerShell in the context of ConfigMgr, this may lead to confusion and frustration as none of the ConfigMgr cmdlets will work if not executed from the site code PSDrive, for instance SMS:\>

I randomly found that the example for Add-CMBoundaryToGroup DOES have a proper example including a link to the Getting Started article and a reference to starting cmdlets from the site drive: https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Add-CMBoundaryToGroup.md#examples

Instead of opening an issue for every single article, I'm sure there's a way to edit all articles using PowerShell or something other to ensure they have a properly formatted example and ideally the reference to Getting Started.

I'm aware of the current backlog and am not looking to criticize, rather to revise and optimize ;)

**Comment by aczechowski** [comment]
I think @ChrisKibble fixed this broadly across the doc set. Some of the newer cmdlets (as I'm updating them) come with `C:\>` by default, so that would be good [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/find-help#product-feedback) (file a frown) to make sure the engineering team changes that by default when creating a new cmdlet. When the new cmdlets have that prompt, it's because there's _not_ an actual example. So once I get things rolling again for public contributions in this repo, I'm hoping the community can help fill in those missing examples. 😄

**Comment by merlinfrombelgium** [comment]
In stead of filing a frown, can't we just spank them for lack of implementing best practice? 😋
