### ISSUE TITLE
Get-CMObject

### ISSUE THREAD

**Issue by Barleyologist** [MicrosoftDocs/sccm-docs-powershell-ref#121]
I would like to be able to confirm the object moved, can we get a 'Get-CMObject' command, or something that reports the Folder location?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 015c02b6-5b69-fb85-7cb8-0df13542d71c
* Version Independent ID: fe4333a1-cf0c-c0c0-4960-eed571a06fd3
* Content: [Move-CMObject - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/move-cmobject?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/Move-CMObject.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Move-CMObject.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by felymich** [comment]
Yes it will make the search easier !!! from the current tables and views how do we get the ObjectID?

**Comment by Quatraxx** [comment]
I get the InputObject this way: 
Move-CMObject -FolderPath "AAA:\Application\Tools\" -InputObject (Get-CMApplication -Name "ApplicationName")

**Comment by aczechowski** [comment]
Thanks  for taking the time to provide feedback on Configuration Manager! This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
