### ISSUE TITLE
Include object path in properties

### ISSUE THREAD

**Issue by Barleyologist** [MicrosoftDocs/sccm-docs-powershell-ref#124]
I can not tell you how many times I have needed Object Path, i.e. which folder is it in.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7884089c-5ea7-b495-b0e1-06035e2ce281
* Version Independent ID: 42ae40d7-3a20-7ab8-faff-77e27c33bfaa
* Content: [Get-CMCollection - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmcollection?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMCollection.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMCollection.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Barleyologist for taking the time to provide feedback on Configuration Manager! This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
