### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by jrudlin** [MicrosoftDocs/sccm-docs-powershell-ref#130]
When will this cmdlet be updated to support ARM deployment with ConfigMgr 1810 and above?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19bfd32d-d3c3-b5ef-37b9-0116d543933c
* Version Independent ID: 6fc374cd-8279-adda-bccb-ce13b3973f67
* Content: [New-CMCloudManagementGateway - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmcloudmanagementgateway?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/New-CMCloudManagementGateway.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMCloudManagementGateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jrudlin for taking the time to provide feedback on Configuration Manager! I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
