### ISSUE TITLE
How do set an Offset value?

### ISSUE THREAD

**Issue by NathanTheGr8** [MicrosoftDocs/sccm-docs-powershell-ref#133]
I want to create a schedule of 2nd Tuesday of the month + 2 days. Going the ADR wizard you can set an offset, I don't see an option in this cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4d670cd-926f-26b3-00b6-176437bd086c
* Version Independent ID: 57df715a-6a85-1362-e5db-9b76ab03df85
* Content: [New-CMSchedule - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmschedule?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/New-CMSchedule.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMSchedule.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
The **OffsetDay** parameter was added in [version 1906](https://docs.microsoft.com/en-us/powershell/sccm/1906-release-notes?view=sccm-ps#new-cmschedule), but this article wasn't updated until early 2020 with the full parameter set. So I think this issue is already resolved. Reopen it if there's still more needed here.
