### ISSUE TITLE
Modify Action on Returncodes

### ISSUE THREAD

**Issue by PehDeh** [MicrosoftDocs/sccm-docs-powershell-ref#142]
Is it possible like in the GUI to modify the Reurncodes, for exampel 3010 -&gt; Success instead of Soft-Reboot. So that no Reboot is triggered?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6548ba0-8146-8b3d-c7fe-5e6f2e2ed946
* Version Independent ID: 6c5a9d23-8912-14e1-1e3a-9eef7fcd13c9
* Content: [Add-CMScriptDeploymentType - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/add-cmscriptdeploymenttype?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Add-CMScriptDeploymentType.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Add-CMScriptDeploymentType.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski 
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @PehDeh, I don't see any option to do that with these cmdlets.

It's an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress.

I'm closing this issue as there's nothing actionable for docs at this time.
