### ISSUE TITLE
-LogonRequirementType parameter description

### ISSUE THREAD

**Issue by NeverEnoughCoffeeMan** [MicrosoftDocs/sccm-docs-powershell-ref#146]
The **-LogonRequirementType** parameter description claims three values (OnlyWhenNoUserLoggedOn, OnlyWhenUserLoggedOn, WhereOrNotUserLoggedOn) yet the accompanying table documents four acceptable values (OnlyWhenNoUserLoggedOn, OnlyWhenUserLoggedOn, WhereOrNotUserLoggedOn, WhetherOrNotUserLoggedOn).

WhereOrNotUserLoggedOn?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd496a69-4a03-ebad-4b09-b6a8525e9a9b
* Version Independent ID: 1ab4c179-f1a7-386e-a6d1-f1711cbe2495
* Content: [Set-CMDeploymentType (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmdeploymenttype?view=sccm-ps#parameters)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMDeploymentType.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMDeploymentType.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @NeverEnoughCoffeeMan for the feedback. This article had a number of issues like that, so I fixed them all by just removing those sentences. The YAML table for each parameter is auto-generated from the module, which includes the possible values. So that additional list in the description is redundant.
The changes will publish live soon with the 2006 content release.
