### ISSUE TITLE
-AllowFallbackForContent

### ISSUE THREAD

**Issue by N5ZY** [MicrosoftDocs/sccm-docs-powershell-ref#151]
Shouldn't this be deprecated?  Fallback is set on boundary groups not on a DP anymore.

**Comment by aczechowski** [comment]
Thanks @N5ZY for taking the time to provide feedback on Configuration Manager! I want to make sure your product feedback gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
