### ISSUE TITLE
-onDemandDistro needed

### ISSUE THREAD

**Issue by N5ZY** [MicrosoftDocs/sccm-docs-powershell-ref#152]
"Enable for on-demand distribution" for a DP is painfully needed in PowerShell.
Having to set this/check this in the GUI is a huge waste of time since it's not even a column in the DP Overview.

**Comment by aczechowski** [comment]
Thanks @N5ZY for taking the time to provide feedback on Configuration Manager! This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
