### ISSUE TITLE
InstallationBehaviorType, LogonRequirementType, RebootBehavior are missing from Get-CMDeploymentType

### ISSUE THREAD

**Issue by Barleyologist** [MicrosoftDocs/sccm-docs-powershell-ref#161]
There missing or I have not been able to locate them

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22ed6802-1a57-f836-2bcb-e04375492903
* Version Independent ID: c63638a7-737e-83e3-518c-f96593c1ebc2
* Content: [Get-CMDeploymentType (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmdeploymenttype?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMDeploymentType.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMDeploymentType.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Barleyologist for taking the time to provide feedback on Configuration Manager! I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.

I wasn't able to find any properties for those in the deployment type. So engineering will need to take the feedback to add those properties.
There's some implicit feedback here though that I've filed an internal item to track: for all the "get" verb cmdlets, listing the properties that are returned, and then even mapping them to the console options. Probably a big effort, but might be worth it.

**Comment by aczechowski** [comment]
I had responded to another of your issues recently about how PowerShell is built on WMI, yet I didn't connect the dots in this context. Until I talked with a colleague on the PowerShell docs team, and he showed me a tip.

If you look at the [Outputs](https://docs.microsoft.com/powershell/module/configurationmanager/get-cmdeploymenttype?view=sccm-ps#outputs) for this cmdlet, you'll see the object is **SMS_DeploymentType**. Which corresponds to the server WMI class [SMS_DeploymentType](https://docs.microsoft.com/mem/configmgr/develop/reference/apps/sms_deploymenttype-server-wmi-class). I didn't see any mention there of those properties (or similar) that you mentioned, so it would be a change in the product to expose those properties.

So I'll look to start adding in some reference links in the future to make these more easily identified.
