### ISSUE TITLE
Language documentation missing and example 2 doesn't work

### ISSUE THREAD

**Issue by heinejeppesen** [MicrosoftDocs/sccm-docs-powershell-ref#179]
Example 2 doesn't seem to work anymore?
One of the parameters specified is deprecated and two overlapping.
Trying with the "-Language "Catalan" gives me New-CMSoftwareUpdateAutoDeploymentRule : No object corresponds to the specified parameters. Works with "English" 

-Language, -LanguageSelection and -O365LanguageSelection should have better documentation.
What do we specify as input? English seems to work, can't get anything else to work - including the "Catalan" example.

Do we specify other languages as "Danish (Denmark)", "Danish" or "Dansk (Danmark)" as my GUI shows the language?
Can't seem to find any documentation on this :-(

Testing on 2002

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a909f32d-5808-1dfc-f835-95fb8b260c54
* Version Independent ID: 9b1587a0-72ba-a5c6-3404-ac26b0797ed9
* Content: [New-CMSoftwareUpdateAutoDeploymentRule (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmsoftwareupdateautodeploymentrule?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/New-CMSoftwareUpdateAutoDeploymentRule.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMSoftwareUpdateAutoDeploymentRule.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @heinejeppesen for the feedback! I did some investigation with this today. I'll share some details below so that you can start using it. I'll make revisions to the doc (as well as the Set- and Get-), and hope to sneak it in with the 2006 content release soon. This issue will auto-close when the change merges.

I tested all of this with version 2006, but I don't think there was any changes to these cmdlets between 2002 and 2006.

In short, all three parameters (-Language, -LanguageSelection, and -O365LanguageSelection) appear to accept the same strings. They currently use the format you see in the UI for language criteria or Windows Update language selection. For now, I'd say ignore the additional languages and more detailed strings you see in the UI for O365 lang selection. Neither New- or Set- would accept those extended languages, only the core set you see with the other language settings.

Here's an example, which I successfully tested:

```powershell
New-CMSoftwareUpdateAutoDeploymentRule -Name "pwsh test ADR" -CollectionId "XYZ0003F" -Language "English","Hungarian","Chinese (Simplified, PRC)" -Enable $false -EnabledAfterCreate $false -RunType DoNotRunThisRuleAutomatically -LanguageSelection "English","Hungarian","Chinese (Simplified, PRC)" -O365LanguageSelection "English","Hungarian","Chinese (Simplified, PRC)"
```

Note the format for the string arrays if you need to specify more than one language.

So in your case, you would just specify "Danish", for example:

```powershell
Set-CMSoftwareUpdateAutoDeploymentRule -Name "AaronCz temp test 1" -O365LanguageSelection "Danish"
Set-CMSoftwareUpdateAutoDeploymentRule -Name "AaronCz temp test 1" -LanguageSelection "Danish"
Set-CMSoftwareUpdateAutoDeploymentRule -Name "AaronCz temp test 1" -Language "Danish"
```

Note: those commands overwrite, they are not additive. 😄

**Comment by heinejeppesen** [comment]
Hi Aaron,

Thanks for getting back to me.
I think I figured out, why the examples didn’t work for me.

I run the console from a Citrix session, due to heavy access restrictions (firewalled off, different network, different domain, PAM etc).
The Citrix servers are apparently configured with Danish as default for the user interface, which would never have happened on any workstation I would normally use.
I accidentally found out, after I started a Explorer.exe \\servername\share<file://servername/share> from the PowerShell session spawned from within the console.
Everything in Explorer is in Danish, so a bit of facepalm was needed.

Unfortunately this affects the input needed for the arguments, which I didn’t really think of before.

This works for me: -LanguageSelection @('English','Dansk') -O365LanguageSelection @('English','Dansk','Polish')
Danish is “Dansk” and the cmdlets will fail, if I write ‘Danish’. All other languages must be provided in English.

Super confusing, but I guess the language name is translated into a LCID behind the scenes.
I would guess at least a lot of Germans, French and Spanish speaking countries, would potentially see this, given the preference for running the OS in native languages 😉

But now you know, should any other non-english speaking ppl comment on this 😉

-Heine

**Comment by aczechowski** [comment]
Thanks @heinejeppesen for sharing your experience for others. If you use Get-CMSoftwareUpdateAutoDeploymentRule and parse the XML, you'll see the lang IDs that the site stores. So the cmdlet and/or Windows is doing some conversion. I suppose it makes sense that if the system UI is another language, then you have to specify the localized name for the language. That's probably a good tip to include here.

As you can tell, this bug isn't fixed yet. I didn't get it in with the 2006 release as I had hoped. But I'm still working on some additional 2006 content for new BitLocker cmdlets, so will try to update this article with these revisions as part of that effort. You'll know when the work is complete and soon to publish as this issue will auto-close when the change merges.
