### ISSUE TITLE
Update Help

### ISSUE THREAD

**Issue by Krytical13** [MicrosoftDocs/sccm-docs-powershell-ref#181]
It appears that the information related to updating the help for the ConfigurationManger module is no longer valid.

```
Version                     : 5.00.8968.1000

PS SFO:\> Update-Help -Module ConfigurationManager
Update-Help : Failed to update Help for the module(s) :
'ConfigurationManager'
The Update-Help command failed because the specified module does not support updatable help. Use Get-Help -Online or
look online for help for the commands in this module.
At line:1 char:1
+ Update-Help -Module ConfigurationManager
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (HelpInfoUri:Uri) [Update-Help], Exception
    + FullyQualifiedErrorId : HelpInfoUriNotFound,Microsoft.PowerShell.Commands.UpdateHelpCommand
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d3cfeb8-c773-1ae5-0975-ea48e20e4c3a
* Version Independent ID: 7794c3e5-20ad-e389-6e18-c70628a3505a
* Content: [Configuration Manager PowerShell cmdlets - Configuration Manager](https://docs.microsoft.com/en-us/powershell/sccm/overview?view=sccm-ps)
* Content Source: [docs-conceptual/overview.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/docs-conceptual/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Krytical13 thanks for the feedback. It's been a known issue for a while, due to a backend bug in the module and where the update help content was stored. I'm actively working with the ConfigMgr engineering team, PowerShell product team, and PowerShell doc team to test a new help pipeline that will synchronize this doc content for the module to a location for update-help to access. I don't have a specific timeframe yet, but keep an eye on the upcoming [technical preview releases](https://docs.microsoft.com/mem/configmgr/core/get-started/technical-preview) for an announcement when we have it ready to evaluate.
