### ISSUE TITLE
{{ Fill ... }} placeholders

### ISSUE THREAD

**Issue by MichielOverweel** [MicrosoftDocs/sccm-docs-powershell-ref#182]
The PowerShell cmdlet reference contains many placeholders, such as "{{ Fill in the Synopsis }}" and/or "{{ Fill <parameter> description }}". Are these going to be replaced by actual, meaningful descriptions, and if so, when?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08ab97f9-ca77-d2f3-1a74-b734033674c5
* Version Independent ID: 01e64fb6-4385-6864-7430-38ac98632aaf
* Content: [ConfigurationManager Module - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/ConfigurationManager.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/ConfigurationManager.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @MichielOverweel thanks for the feedback. We have limited resources to maintain the over 1100 cmdlet articles for this module (along with the 3200 articles in ConfigMgr core docs). Starting with version 2002, the article for any new cmdlet should be mostly complete. We have an internal tracking item to go back and pick up older cmdlet articles when we have time, but it's honestly not our highest priority due to relatively low page views. 

I literally just fixed a backend problem with our repos so that we can finally accept public contributions again. I'll be going through the backlog of pull requests shortly. Because of our limited resources for this content, we need to rely on community support from members like you to assist. If you have a sample example to share for this cmdlet, you can either share that via this feedback system, or submit an edit to the article to contribute your example. For more information, see [How to use the Configuration Manager docs](https://docs.microsoft.com/mem/configmgr/core/understand/use-docs).

TIP: if you update the "synopsis" section on a specific article, then the next time we run the PlatyPS automation, it updates the one-liner on this module overview page.
