### ISSUE TITLE
CM-Collection Lock State

### ISSUE THREAD

**Issue by Barleyologist** [MicrosoftDocs/sccm-docs-powershell-ref#188]
Documentation does not indicate it Get-CMObjectLockDetails will getting locking information for a CM Collection.  Get-CMObjectLockDetails work for every other object I enter except collections.

(Get-CMCollection -Name "Collection Name" | Get-CMObjectLockDetails) does not return any information.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77163ed7-2e51-6ab4-ed07-2420f5ffad7e
* Version Independent ID: 8a550f8e-7758-3596-3452-b8cde373eb12
* Content: [Get-CMObjectLockDetails (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmobjectlockdetails?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMObjectLockDetails.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMObjectLockDetails.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Barleyologist, I don't think SEDO locks apply to collections. See [ConfigMgr SEDO](https://docs.microsoft.com/mem/configmgr/develop/core/understand/sedo). It's possible that list is out of date, but since collections have been around a while 😉 I would expect it to be on the list if it applies.

But I think we can expand this article to include some additional info about SEDO, especially with a cross-link to the above article for more info.
