### ISSUE TITLE
this needs more info, any update ?

### ISSUE THREAD

**Issue by reepz** [MicrosoftDocs/sccm-docs-powershell-ref#190]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d2b50ee-7b06-f5d0-03e2-885051234a41
* Version Independent ID: a75e595a-e6e4-4187-223b-96d709ef74f3
* Content: [New-CMRequirementRuleExpression (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmrequirementruleexpression?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/New-CMRequirementRuleExpression.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMRequirementRuleExpression.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by reepz** [comment]
no info!

**Comment by aczechowski** [comment]
Hi @reepz thanks for the feedback. We have limited resources to maintain the over 1100 cmdlet articles for this module (along with the 3200 articles in ConfigMgr core docs). Starting with version 2002, the article for any new cmdlet should be mostly complete. We have an internal tracking item to go back and pick up older cmdlet articles when we have time, but it's honestly not our highest priority due to relatively low page views.
I'm closing this issue because it's a known issue across a number of articles, and we have an internal tracking item.
