### ISSUE TITLE
Lacks Example, Desc, and Synopsis

### ISSUE THREAD

**Issue by NathanTheGr8** [MicrosoftDocs/sccm-docs-powershell-ref#194]
Title

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ef7dc5-65f2-5f8e-f7b1-155345aa3b97
* Version Independent ID: 9f95facc-3072-8317-5311-57fc78114780
* Content: [Get-CMBoundaryGroupSiteSystem (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmboundarygroupsitesystem?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMBoundaryGroupSiteSystem.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMBoundaryGroupSiteSystem.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @NathanTheGr8 thanks for the feedback. We have limited resources to maintain the over 1100 cmdlet articles for this module (along with the 3200 articles in ConfigMgr core docs). Starting with version 2002, the article for any new cmdlet should be mostly complete. We have an internal tracking item to go back and pick up older cmdlet articles when we have time, but it's honestly not our highest priority due to relatively low page views.
I'm closing this issue because it's a known issue across a number of articles, and we have an internal tracking item.
