### ISSUE TITLE
Index?

### ISSUE THREAD

**Issue by gwblok** [MicrosoftDocs/sccm-docs-powershell-ref#202]
[Enter feedback here]
I'm trying to use this commandlet to add a step, which I can do.
However I can't control the placement very well.
the example of "$index" isn't overly helpful.  

I need to know how to add a step into a group.
I've used "Get-CMTaskSequenceStep" to see if I can find the index for a current step, which I couldn't figure out either.

Is there a page that explains how to create things in the order you want, add things into groups, etc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cca77e1-3393-5496-2f67-3bbf8fb93d9a
* Version Independent ID: f5c9a479-8364-7fe0-00de-dcc8f2867437
* Content: [Add-CMTaskSequenceStep (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/add-cmtasksequencestep?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Add-CMTaskSequenceStep.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Add-CMTaskSequenceStep.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by gwblok** [comment]
Ok, so I need to use a different commandlet to add a step to a group in a TS. Set-CMTaskSequenceGroup
But still unsure how I can properly arrange steps in an order.  Is there a commandlet to get the index value of another step, so I can then use that value to place a new step in front of or behind a reference step?

**Comment by gguyza001** [comment]
MICROSOFT COMMUNITY TRAINING<br><br>
________________________________________<br><br>
These license terms are an agreement between you and Microsoft Corporation (or one of its affiliates). They apply to the managed application and Android application software named above, i.e., they apply to the preview access and use of the “Microsoft Community Training”. IF YOU COMPLY WITH THESE LICENSE TERMS, YOU HAVE THE RIGHTS BELOW. BY USING THE MANAGED APPLICATION, YOU ACCEPT THESE TERMS.<br><br>
1.	INSTALLATION AND USE RIGHTS.<br><br>
a)	General. Subject to the terms and conditions of this agreement, Microsoft grants you a limited, non-exclusive, non-transferable right to use the managed application within Microsoft Azure. If you obtained access to software or open source components through the managed application, you may use the software only in virtual machines in Microsoft Azure deployed from the managed application. Use of Microsoft Azure resources and services deployed by the managed application (but not the managed application itself) shall be governed by agreement under which you have obtained Microsoft Azure services from Microsoft or an authorized reseller and the applicable privacy policy (see https://azure.microsoft.com/en-us/support/legal/).  Your Azure subscription will be billed for fees and applicable taxes associated with use of Azure resources and services deployed by this template until your use is discontinued.<br><br>
Further, You may install and use copies of the software to develop and test your applications, solely for the purpose stated above and otherwise for your internal business purposes. You may make backup copies of the software for the sole purpose of reinstalling the software. The software may include other Microsoft applications. These license terms apply to those included applications, if any, unless other license terms are provided with the other Microsoft applications.<br><br>
b)	Third Party Software. This managed application enables you to obtain software applications from other sources. Those applications are offered and distributed by third parties under their own license terms.  Microsoft is not developing, distributing or licensing those applications to you, but instead, as a convenience, enables you to use this managed application to obtain those applications directly from the application providers.  By using the managed application, you acknowledge and agree that you are obtaining the applications directly from the third party providers and under separate license terms, and that it is your responsibility to locate, understand and comply with those license terms.  Microsoft grants you no license rights for third-party software or applications that is obtained using this managed application.<br><br>
Further, the software may include third party applications that are licensed to you under this agreement or under their own terms. License terms, notices, and acknowledgements, if any, for the third party applications may be accessible online at http://aka.ms/thirdpartynotices or in an accompanying notices file. Even if such applications are governed by other agreements, the disclaimer, limitations on, and exclusions of damages below also apply to the extent allowed by applicable law.<br><br>
c)	Open Source Components. The software may contain third party copyrighted software licensed under open source licenses with source code availability obligations. Copies of those licenses are included in the ThirdPartyNotices file or other accompanying notices file. You may obtain the complete corresponding source code from Microsoft if and as required under the relevant open source license by sending a money order or check for $5.00 to: Source Code Compliance Team, Microsoft Corporation, 1 Microsoft Way, Redmond, WA 98052, USA. Please write “source code for Microsoft Community Training” in the memo line of your payment. You may also find a copy of the source at http://aka.ms/getsource.<br><br>
d)	Microsoft Services Agreement. Some features of the software provide access to, or rely on, online services. The use of those services (but not the software) is governed by the separate terms and privacy policies in the Microsoft Services Agreement http://go.microsoft.com/fwlink/?linkid=398923. Please read them. The services may not be available in all regions.<br><br>
e)	Competitive Benchmarking. If you are a direct competitor, and you access or use the software for purposes of competitive benchmarking, analysis, or intelligence gathering, you waive as against Microsoft, its subsidiaries, and its affiliated companies (including prospectively) any competitive use, access, and benchmarking test restrictions in the terms governing your software to the extent your terms of use are, or purport to be, more restrictive than Microsoft’s terms. If you do not waive any such purported restrictions in the terms governing your software, you are not allowed to access or use this software, and will not do so.<br><br>
2.	PRE-RELEASE SOFTWARE. The managed application is a pre-release version (“Preview”). It may not operate correctly. It may be different from the commercially released version. Previews may employ lesser or different privacy and security measures than those typically present in Microsoft products and services which are a commercially released version. You should not use previews to process personal data or other data that is subject to legal or regulatory compliance requirements.<br><br>
3.	FEEDBACK. If you give feedback about the managed application to Microsoft, you give to Microsoft, without charge, the right to use, share and commercialize your feedback in any way and for any purpose. You will not give feedback that is subject to a license that requires Microsoft to license its software or documentation to third parties because Microsoft includes your feedback in them. These rights survive this agreement. <br><br>
4.	DATA COLLECTION. The software may collect information about you and your use of the managed application and the software and send that to Microsoft. Microsoft may use this information to provide services and improve Microsoft’s products and services. Your opt-out rights, if any, are described in the product documentation. Some features in the managed application and the software may enable collection of data from users of your applications that access or use the managed application or the software. If you use these features to enable data collection in your applications, you must comply with applicable law, including getting any required user consent, and maintain a prominent privacy policy that accurately informs users about how you use, collect, and share their data. You can learn more about Microsoft’s data collection and use in the product documentation and the Microsoft Privacy Statement at https://privacy.microsoft.com/en-us/privacystatement. You agree to comply with all applicable provisions of the Microsoft Privacy Statement.<br><br>
5.	MANAGED APPLICATIONS. By agreeing to the terms of this Agreement, you give permission to Microsoft to have administrative level access to one or more Azure resources in order to provide management and support services, as may be applicable, for the managed application. For deploying the managed application various action may be performed by Microsoft, which may include the deployment of one or more Azure resources or Marketplace offerings and/or transmission of the information provided by you to one or more parties, as specified in the managed application. You are responsible for reviewing the text of the managed application to determine which actions will be performed and which resources or offerings will be deployed, and for locating and reviewing the pricing and legal terms associated with those resources or offerings.<br><br>

**Comment by aczechowski** [comment]
Hey @gwblok I forgot about this issue, but made some updates back in May to this article that includes more info on the index. Take a look at the revisions. I'm going to close this issue...if you still have questions, let me know.
