### ISSUE TITLE
Please add an example

### ISSUE THREAD

**Issue by Anoni-Mouse** [MicrosoftDocs/sccm-docs-powershell-ref#209]
[Enter feedback here]

PS XYZ:\> {{ Add example code here }} ????
Please add a real example
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e3e8e8a-acd2-9be1-cb89-3a3cdcfd7512
* Version Independent ID: 07321564-9702-7a69-279f-29ee3ba68959
* Content: [New-CMAdministrativeUserPermission (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmadministrativeuserpermission?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/New-CMAdministrativeUserPermission.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMAdministrativeUserPermission.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Anoni-Mouse thanks for the feedback. We have limited resources to maintain the over 1100 cmdlet articles for this module (along with the 3200 articles in ConfigMgr core docs). Starting with version 2002, the article for any new cmdlet should be mostly complete. We have an internal tracking item to go back and pick up older cmdlet articles when we have time, but it's honestly not our highest priority due to relatively low page views. When we do have time to work on that, we'll prioritize the list by article popularity (page views).
