### ISSUE TITLE
Verbose output cannot be suppressed

### ISSUE THREAD

**Issue by cantoris** [MicrosoftDocs/sccm-docs-powershell-ref#243]
Used inside an advanced function with -Verbose active, this cmdlet is giving me verbose output that I can't prevent even when using -Verbose:$false on the cmdlet.  Am using CM2107.
e.g. Using `$s = New-CMSchedule -RecurInterval Days -RecurCount 1 -Verbose:$false` outputs "VERBOSE: Creating embedded object instance of class 'SMS_ST_RecurInterval'".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e4b931f-23bc-49e8-efe7-d15ce9a55401
* Version Independent ID: 57df715a-6a85-1362-e5db-9b76ab03df85
* Content: [New-CMSchedule (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmschedule?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/New-CMSchedule.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMSchedule.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @cantoris for taking the time to provide feedback on Configuration Manager! I'm sorry that you're having issues with this cmdlet, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/powershell/sccm/overview#feedback-for-powershell) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
