### ISSUE TITLE
What exactly does this cmdlet do?

### ISSUE THREAD

**Issue by elang-bmrn** [MicrosoftDocs/sccm-docs-powershell-ref#25]
Could you please verify that this cmdlet is working correctly? In CB 1806, its output does not match what is visible in the console for data such as numfailed / numinstalled / nummissing; only the numtotal and numunknown information is present, despite an hourly summarization schedule.

When passed the output of a single input object (a software update deployment object) , it also returns an array of items, instead of just one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 567498c9-0abe-19de-a832-1606fba9d0db
* Version Independent ID: 5ba2bfb6-b909-b813-b6d3-6635f3d5382a
* Content: [Get-CMSoftwareUpdateDeploymentStatus (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmsoftwareupdatedeploymentstatus?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMSoftwareUpdateDeploymentStatus.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMSoftwareUpdateDeploymentStatus.md)

**Comment by aczechowski** [comment]
I think there's a product bug here. I'm not entirely sure where though. With version 2006 I get the same results, NumTotal is correct, but everything is NumUnknown and no granularity of the other values. I know summarization can cause mismatched data, but this seems extreme. And I tried passing the output of this cmdlet to Get-CMDeploymentStatusDetails for more details, but that failed. It works with Get-CMPackageDeploymentStatus, so I would expect it to be consistent.

I'd generally suggest that you file a frown yourself from the console, so that you can track the status of the bug. If you see this note and want to do that, please do. I'll file a bug myself, but the engineering team can dupe it out on yours if you file one.

I'll make a few tweaks to this article to help clean it up. Thanks for the feedback.
This issue will close when the associated PR merges. The changes will go live soon with the 2006 content release.
