### ISSUE TITLE
maybe not true.."you can specify the path of the MSI file or the path to the folder that contains the MSI."

### ISSUE THREAD

**Issue by PaulKlerkx** [MicrosoftDocs/sccm-docs-powershell-ref#252]
Hi,

I was excited to see this entry on your page, however I don't think it is true.  

**_"Starting in version 2107, you can specify the path of the MSI file or the path to the folder that contains the MSI."_**

i have logged this in the techcommunity forums (about 12 months ago) and my recent post gives details of attempting this in 2107. 

https://techcommunity.microsoft.com/t5/configuration-manager/set-cmmsideploymenttype/m-p/3096573#M1192 

If I didn't get the command right, maybe an example of usage on the page might be useful .  (to set a folder path as the location for content that is)

folllowing are some examples of what DOES NOT work.  

Set-CMMSIDeploymentType –ApplicationName "My App V5.19.0" –DeploymentTypeName "My App V5.19.0 - Windows Installer (*.msi file)" –ContentLocation "\\MyServer\MyPath\My App\5.19.0"

Set-CMMSIDeploymentType –ApplicationName "My App V5.19.0" –DeploymentTypeName "My App V5.19.0 - Windows Installer (*.msi file)" –ContentLocation "\\MyServer\MyPath\My App\5.19.0\"

Set-CMMSIDeploymentType –ApplicationName 'My App V5.19.0' –DeploymentTypeName 'My App V5.19.0 - Windows Installer (*.msi file)' –ContentLocation '\\MyServer\MyPath\My App\5.19.0'

**Comment by aczechowski** [comment]
Hi @PaulKlerkx sorry you're having issues. Engineering double-checked the doc and confirmed it's correct. So I'm going to close this issue for now.

One suggestion: try putting a trailing slash `\` at the end of the parameter value.

If that doesn't work, please file a frown from the console and include additional details as noted for PowerShell: https://docs.microsoft.com/powershell/sccm/overview#feedback-for-powershell

If that _does_ work, then let's reopen this issue to get a note added for that parameter that it needs to include the trailing slash for the directory. And/or add an example as you suggested. (And if you want to just submit that change yourself instead of reopening this issue, that would be awesome too! 😄 )
