### ISSUE TITLE
Publish-CMThirdPartySoftwareUpdateContent| The -Confirm Parameter does not work

### ISSUE THREAD

**Issue by Johannes0001** [MicrosoftDocs/sccm-docs-powershell-ref#260]
You always must confirm if you want to publish the ThirdPartySoftwareUpdateContent. 
Even if you try to suppress the message, you still must confirm it. 

```
$ConfirmPreference=”High” 
Publish-CMThirdPartySoftwareUpdateContent -CIId $ThirdPartySoftware.CI_ID -Confirm:$false
```
![CDViewer_TC8U33MmJE](https://user-images.githubusercontent.com/104502760/166232609-b2c7dca8-5e7c-47d8-b2cf-d505d7be5354.png)

**Comment by aczechowski** [comment]
Thanks @Johannes0001 for sharing this information. In this case, you need to file product feedback to report this issue. See the [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress.

I'm closing this issue as there's nothing actionable for docs at this time.
