### ISSUE TITLE
This cmdlet is missing CMG or Cloud DP support?

### ISSUE THREAD

**Issue by Btreyo** [MicrosoftDocs/sccm-docs-powershell-ref#28]
receive an error via gui or cmdlet when associating to a CMG DP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 984da656-77c8-fbcf-78d6-4940cdc37416
* Version Independent ID: 90c228a1-77b9-0aaf-1d4c-3d09c5387d89
* Content: [New-CMBootableMedia (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmbootablemedia?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/New-CMBootableMedia.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMBootableMedia.md)

**Comment by FISHMANPET** [comment]
I don't believe CMG or Cloud DP is supported for OSD, so I would assume by extension that it's not a valid source for a WinPE client to pull config info for, but someone at MS would have to confirm that

**Comment by aczechowski** [comment]
Thanks for taking the time to provide feedback on Configuration Manager! I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
