### ISSUE TITLE
Example 2 Does not work

### ISSUE THREAD

**Issue by RicoRosenheim** [MicrosoftDocs/sccm-docs-powershell-ref#73]
The example 2 does not work as described.
Error: 
Approve-CMDevice : The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6430f4aa-f96b-4720-1ac9-a336c082cd78
* Version Independent ID: d3455ef0-301e-1e8f-cd19-33dd2d8875db
* Content: [Approve-CMDevice (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/approve-cmdevice?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/Approve-CMDevice.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Approve-CMDevice.md)

**Comment by aczechowski** [comment]
Thanks @RicoRosenheim for the feedback. I started to play with this cmdlet to fix the article, and I wonder if it's a bug with the cmdlet. The **Block-CMDevice** cmdlet works just fine with either of the following:

```powershell
Get-CMDevice -Name "WIN10-86-33" | Block-CMDevice
```

```powershell
$device Get-CMDevice -Name "TestVlan-site2"
Block-CMDevice -InputObject $device
```

But the same examples with **Approve-CMDevice** fails in both instances with the error you note or:
`Approve-CMDevice : Cannot bind argument to parameter 'InputObject', because PSTypeNames of the argument do not match
the PSTypeName required by the parameter: IResultObject#SMS_CombinedDeviceResources.`

It doesn't make sense to me that one works and the other doesn't. 
I don't already see a bug on it, so suggest that you file a frown from the console. I'll check with the engineering team as well to make sure I'm missing something obvious.

**Comment by aczechowski** [comment]
Yep, it's a bug. I just filed one internally. I'm closing this issue as there's nothing currently actionable for docs.
(internal reference 7914538)
